package com.charleskelly.magic.utils;

/**
 * Created by Charles Kelly
 * <P>
 *     Separate reporting for exceptions generated by MathUtility
 * </P>
 * <p></p>
 * @author Charles Kelly
 */
public class MathUtilityException extends Exception
{
    public MathUtilityException(String message)
    {
        super(message);
    }
}

